#!/bin/sh

## autoload vcs and colors
autoload -Uz vcs_info
autoload -U colors && colors

# enable only git 
zstyle ':vcs_info:*' enable git 

# setup a hook that runs before every ptompt. 
precmd_vcs_info() { vcs_info }
precmd_functions+=( precmd_vcs_info )
setopt prompt_subst

# add a function to check for untracked files in the directory.
# from https://github.com/zsh-users/zsh/blob/master/Misc/vcs_info-examples
zstyle ':vcs_info:git*+set-message:*' hooks git-untracked
# 
+vi-git-untracked(){
    if [[ $(git rev-parse --is-inside-work-tree 2> /dev/null) == 'true' ]] && \
        git status --porcelain | grep '??' &> /dev/null ; then
        # This will show the marker if there are any untracked files in repo.
        # If instead you want to show the marker only if there are untracked
        # files in $PWD, use:
        #[[ -n $(git ls-files --others --exclude-standard) ]] ; then
        hook_com[staged]+='!' # signify new files with a bang
    fi
}

zstyle ':vcs_info:*' check-for-changes true
zstyle ':vcs_info:git:*' formats " %{$fg_bold[black]%}(%{$fg_bold[blue]%}%m%u%c%{$fg[cyan]%}%{$fg_bold[white]%} %b%{$fg_bold[black]%})"

# format our main prompt for hostname current folder, and permissions.
function preexec() {
  timer=$(date +%s%3N)
}
function precmd() {
    print ""
    if [ $timer ]; then
        local now=$(date +%s%3N)
        local d_ms=$(($now-$timer))
        local d_s=$((d_ms / 1000))
        local ms=$((d_ms % 1000))
        local s=$((d_s % 60))
        local m=$(((d_s / 60) % 60))
        local h=$((d_s / 3600))
        if ((h > 0)); then elapsed=${h}h${m}m
        elif ((m > 0)); then elapsed=${m}m${s}s
        elif ((s > 0)); then elapsed=${s}.$((ms / 100))s
        else elapsed=${ms}ms
        fi
        if [[ $elapsed == ${ms}ms ]]; then
            time=""
        else
            time="[took ${elapsed}]"
        fi
        export RPROMPT="%F%{$fg_bold[yellow]%}${time}%{$reset_color%}"
        unset timer
    fi
}

PROMPT="%F%{$fg[magenta]%}%c %(?:%{$fg_bold[green]%}:%{$fg_bold[red]%})%{$reset_color%}"
PROMPT+="\$vcs_info_msg_0_ "
# TODO look into this for more colors
# https://stevelosh.com/blog/2010/02/my-extravagant-zsh-prompt/
# also ascii escape codes

