#! /bin/sh
bspc rule -r "*"

#Start polybar first
bash ~/.config/polybar/launch.sh &

# Variable Defines
color0=#3B4252
color4=#D8DEE9

# Make sure sxhkd is always running
while :; do
    if pgrep -x sxhkd > /dev/null; then
        true
    else
        sxhkd &
    fi
done &

#Fix Mouse cursor on startup
xsetroot -cursor_name left_ptr

#Set Keyboard Layout
setxkbmap -layout us

#Monitor Config
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

#BSPWM Config
bspc config border_width        2
bspc config top_padding         30
bspc config right_padding       5
bspc config left_padding        5
bspc config bottom_padding      5
bspc config window_gap          2
bspc config top_monocle_padding  0
bspc config right_monocle_padding 0
bspc config left_monocle_padding 0
bspc config bottom_monocle_padding 0

bspc config focused_border_color "$color0"
bspc config normal_border_color  "#00000000"
bspc config active_border_color  "$color0"
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false

#Application Rules
bspc rule -a Gimp desktop='^8' follow=on
bspc rule -a wine desktop='^9' state=floating follow=on
bspc rule -a variety state=floating
bspc rule -a Chromium desktop='^1'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Discord desktop='^6'
bspc rule -a Yad state=floating
bspc rule -a Screenkey manage=off
bspc rule -a spotify desktop='^7'
bspc rule -a mpv desktop='^8' state=fullscreen
bspc rule -a Signal desktop='^6'

#Auto-Start
nm-applet --indicator &
gammy &
