#!/bin/sh

USERXSESSION="$XDG_CACHE_HOME/X11/xsession"
USERXSESSIONRC="$XDG_CACHE_HOME/X11/xsessionrc"

# Don't Randomly Turn off
xset s off
xset -dpms
xset s noblank

# For annoying beeping sounds
xset -b

# Speedy keys
xset r rate 300 50

# For the X-shaped cursor
xsetroot -cursor_name left_ptr

# Swap escape and caps
setxkbmap -option caps:swapescape

# Load Xresources
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &

# Wallpaper
# feh --no-fehbg --bg-fill -z ~/.config/backgrounds &
~/.local/bin/wall &

# Network Manager Applet
nm-applet --indicator &

# Compositor
picom --experimental-backends &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Torrent daemon
# transmission-daemon &

# Hide mouse when typing
unclutter &

# Clipboard Manager
greenclip daemon &

# Screenshot utility
flameshot &

# Screen temperature
gummy start &

#Bluetooth manager
#blueberry-tray &

# Power manager
~/.local/bin/bat_state &

# File manager
thunar --daemon &

# Notification Daemon
/usr/bin/dunst &

# Lockscreen
xss-lock -- betterlockscreen -l blur &

# exec qtile start

# exec dwmblocks &
# exec dwm

exec xmonad
