#!/bin/sh

USERXSESSION="$XDG_CACHE_HOME/X11/xsession"
USERXSESSIONRC="$XDG_CACHE_HOME/X11/xsessionrc"

# Don't Randomly Turn off
xset s off
xset -dpms
xset s noblank

# For annoying beeping sounds
xset -b

# Speedy keys
xset r rate 300 50

# Swap escape and caps
setxkbmap -option caps:swapescape

# Load Xresources
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &

# Wallpaper
feh --no-fehbg --bg-fill ~/.config/background.jpg &

# Network Manager Applet
nm-applet --indicator &

# Compositor
picom --experimental-backends &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Hide mouse when typing
xbanish &

# Clipboard Manager
greenclip daemon &

# Screenshot utility
flameshot &

# Screen temperature
gummy start &

# Power manager
xfce4-power-manager &

# Notification Daemon
#/usr/lib/xfce4/notifyd/xfce4-notifyd &
/usr/bin/dunst &

# Lockscreen
xss-lock -- betterlockscreen -l blur &

# exec bspwm
# exec qtile start
exec dwmblocks &
exec dwm
